package com.aironman.core.pojos;
// Generated 16-abr-2012 11:00:31 by Hibernate Tools 3.2.1.GA


import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * HistoricoUsuariosItems generated by hbm2java
 */
@Entity
@Table(name="historicoUsuariosItems"
    ,catalog="Store"
)
public class HistoricoUsuariosItems  implements java.io.Serializable {

     private static final Log log = LogFactory.getLog(HistoricoUsuariosItems.class);

     //TODO generar adecuadamente este serial
     private static final long serialVersionUID = 1L;
     
     private Long id;
     private String legajo;
     private String isbn;
     private Timestamp fechaUsuarioItem;

    public HistoricoUsuariosItems() {
        if (log.isDebugEnabled()){
            log.info("CONSTRUCTOR SIN TIPO HistoricoUsuariosItems...");
        }
    }

    public HistoricoUsuariosItems(String _legajo,String _isbn,Timestamp _fechaUsuarioItem) {
       
       if (log.isDebugEnabled()){
            log.info("CONSTRUCTOR TIPado HistoricoUsuariosItems...");
       }
       this.legajo=_legajo;
       this.isbn=_isbn;
       this.fechaUsuarioItem=_fechaUsuarioItem;
    }
    
    @Column(name="fechaUsuarioItem", nullable=false, length=10)
    public Timestamp getFechaUsuarioItem()
    {
        return fechaUsuarioItem;
    }

    public void setFechaUsuarioItem(Timestamp fechaUsuarioItem)
    {
        this.fechaUsuarioItem = fechaUsuarioItem;
    }

    @Column(name="isbn", nullable=false, length=20)
    public String getIsbn()
    {
        return isbn;
    }

    public void setIsbn(String isbn)
    {
        this.isbn = isbn;
    }

    @Column(name="legajo", nullable=false, length=100)
    public String getLegajo()
    {
        return legajo;
    }

    public void setLegajo(String legajo)
    {
        this.legajo = legajo;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId()
    {
        return id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }
}


