package com.aironman.core.pojos;
// Generated 17-abr-2012 12:38:27 by Hibernate Tools 3.2.1.GA


import java.sql.Timestamp;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;

/**
 * HistoricoItemsApuntesId generated by hbm2java
 */
@Embeddable
public class HistoricoItemsApuntesId  implements java.io.Serializable {

    //TODO generar adecuadamente este serial
     private static final long serialVersionUID = 1L;

     
    private long claveApunte;
    private String isbn;
    private Timestamp fecha;

    public HistoricoItemsApuntesId() {
    }

    public HistoricoItemsApuntesId(long claveApunte, String isbn, Timestamp fecha) {
       this.claveApunte = claveApunte;
       this.isbn = isbn;
       this.fecha = fecha;
    }
   

    @Column(name="claveApunte", nullable=false)
    public long getClaveApunte() {
        return this.claveApunte;
    }
    
    public void setClaveApunte(long claveApunte) {
        this.claveApunte = claveApunte;
    }

    @Column(name="isbn", nullable=false, length=20)
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Timestamp fecha) {
        this.fecha = fecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HistoricoItemsApuntesId) ) return false;
		 HistoricoItemsApuntesId castOther = ( HistoricoItemsApuntesId ) other; 
         
		 return (this.getClaveApunte()==castOther.getClaveApunte())
 && ( (this.getIsbn()==castOther.getIsbn()) || ( this.getIsbn()!=null && castOther.getIsbn()!=null && this.getIsbn().equals(castOther.getIsbn()) ) )
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getClaveApunte();
         result = 37 * result + ( getIsbn() == null ? 0 : this.getIsbn().hashCode() );
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         return result;
   }   


}


