package com.aironman.core.pojos;
// Generated 16-abr-2012 11:00:31 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="Usuarios"
    ,catalog="Store"
)
public class Usuarios  implements java.io.Serializable {

     private static final Log log = LogFactory.getLog(Usuarios.class);

     //TODO generar adecuadamente este serial
     private static final long serialVersionUID = 1L;
     
     private String legajo;
     private String nombre;
     private String numeroCC;
     private String email;
     private String password;
     private String passConfirm;
     private String direccion;
     private String status;
     private String lat;
     private String lon;
    public Usuarios() {
        if (log.isDebugEnabled()){
            log.info("Constructor sin tipo Usuarios...");
        }
        
    }

	
    public Usuarios(String legajo, String nombre, String numeroCc, String email, String password, String passConfirm, String direccion, String status) {
        this.legajo = legajo;
        this.nombre = nombre;
        this.numeroCC = numeroCc;
        this.email = email;
        this.password = password;
        this.passConfirm = passConfirm;
        this.direccion = direccion;
        this.status = status;

    }
    public Usuarios(String legajo, String nombre, String numeroCc, String email, String password, String passConfirm, String direccion, String status, String lat, String lon) {
       this.legajo = legajo;
       this.nombre = nombre;
       this.numeroCC = numeroCc;
       this.email = email;
       this.password = password;
       this.passConfirm = passConfirm;
       this.direccion = direccion;
       this.status = status;
       this.lat = lat;
       this.lon = lon;
    }
   
    @Id 
    @Column(name="legajo", unique=true, nullable=false, length=100)
    public String getLegajo() {
        return this.legajo;
    }
    
    public void setLegajo(String legajo) {
        this.legajo = legajo;
    }
    
    @Column(name="nombre", nullable=false, length=40)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="numeroCC", nullable=false, length=20)
    public String getNumeroCC() {
        return this.numeroCC;
    }
    
    public void setNumeroCC(String numeroCc) {
        this.numeroCC = numeroCc;
    }
    
    @Column(name="email", nullable=false, length=20)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="password", nullable=false, length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="passConfirm", nullable=false, length=5)
    public String getPassConfirm() {
        return this.passConfirm;
    }
    
    public void setPassConfirm(String passConfirm) {
        this.passConfirm = passConfirm;
    }
    
    @Column(name="direccion", nullable=false, length=30)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="status", nullable=false, length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="lat", length=10)
    public String getLat() {
        return this.lat;
    }
    
    public void setLat(String lat) {
        this.lat = lat;
    }
    
    @Column(name="lon", length=10)
    public String getLon() {
        return this.lon;
    }
    
    public void setLon(String lon) {
        this.lon = lon;
    }
}