package com.aironman.core.pojos;
// Generated 16-abr-2012 11:00:31 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Items generated by hbm2java
 * XmlRootElement es usado para serializar /deserializar el objeto para convertirlo en xml o json
 */
@SuppressWarnings("restriction")
@XmlRootElement(name = "items")
@Entity
@Table(name="Items"
    ,catalog="Store"
)
public class Items  implements java.io.Serializable {

     //TODO generar adecuadamente este serial
     private static final long serialVersionUID = 1L;
     
     private String isbn;
     private String descripcion;
     private float precio;
     private int numUnidades;

    public Items() {
    }

    public Items(String isbn, String descripcion, float precio, int numUnidades) {
       this.isbn = isbn;
       this.descripcion = descripcion;
       this.precio = precio;
       this.numUnidades = numUnidades;
    }
   
     @Id 
    
    @Column(name="isbn", unique=true, nullable=false, length=10)
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    
    @Column(name="descripcion", nullable=false, length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="precio", nullable=false, precision=12, scale=0)
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    
    @Column(name="numUnidades", nullable=false)
    public int getNumUnidades() {
        return this.numUnidades;
    }
    
    public void setNumUnidades(int numUnidades) {
        this.numUnidades = numUnidades;
    }

    @Override
    public String toString()
    {
        StringBuffer sb = new StringBuffer();
        sb.append(" ITEM<isbn>: ").append(isbn);
        sb.append(" ITEM<descripcion>: ").append(descripcion);
        sb.append(" ITEM<precio>: ").append(precio);
        sb.append(" ITEM<numUnidades>: ").append(numUnidades);
        return sb.toString();
    }

}


