package com.aironman.core.pojos;
// Generated 17-abr-2012 12:38:27 by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HistoricoItemsApuntes generated by hbm2java
 */
@Entity
@Table(name="historicoItemsApuntes"
    ,catalog="Store"
)
public class HistoricoItemsApuntes  implements java.io.Serializable {

    //TODO generar adecuadamente este serial
    private static final long serialVersionUID = 1L;

    private HistoricoItemsApuntesId id;

    public HistoricoItemsApuntes() {
    }

    public HistoricoItemsApuntes(HistoricoItemsApuntesId id) {
       this.id = id;
    }
   
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="claveApunte", column=@Column(name="claveApunte", nullable=false) ), 
        @AttributeOverride(name="isbn", column=@Column(name="isbn", nullable=false, length=20) ), 
        @AttributeOverride(name="fecha", column=@Column(name="fecha", nullable=false, length=10) ) } )

    public HistoricoItemsApuntesId getId() {
        return this.id;
    }
    
    public void setId(HistoricoItemsApuntesId id) {
        this.id = id;
    }

}


